"""
Pydantic data models for the Agentic AI Healthcare System.

Defines the core data structures used across all components:
orchestrator, agents, guardrails, and monitoring.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ─── Enums ───────────────────────────────────────────────────────────────────


class InquiryCategory(str, Enum):
    """Categories of patient inquiries the system can handle."""
    APPOINTMENT = "appointment"
    PRESCRIPTION = "prescription"
    LAB_RESULT = "lab_result"
    INSURANCE = "insurance"
    ESCALATION = "escalation"
    UNKNOWN = "unknown"


class EscalationPriority(str, Enum):
    """Priority levels for human escalation."""
    P1_IMMEDIATE = "P1_IMMEDIATE"       # Life-threatening, < 1 min
    P2_URGENT = "P2_URGENT"             # Controlled substances, distress, < 15 min
    P3_STANDARD = "P3_STANDARD"         # Low confidence, explicit request, < 1 hour
    P4_REVIEW = "P4_REVIEW"             # Quality review, < 24 hours


class GuardrailStatus(str, Enum):
    """Result of a guardrail check."""
    PASSED = "passed"
    BLOCKED = "blocked"
    WARNING = "warning"


class AgentType(str, Enum):
    """Types of agents in the system."""
    ORCHESTRATOR = "orchestrator"
    APPOINTMENT = "appointment"
    PRESCRIPTION = "prescription"
    LAB_REPORT = "lab_report"
    ESCALATION = "escalation"


class AlertSeverity(str, Enum):
    """Severity levels for monitoring alerts."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


# ─── Core Models ─────────────────────────────────────────────────────────────


class IntentClassification(BaseModel):
    """Result of classifying a patient's inquiry intent."""
    category: InquiryCategory
    confidence: float = Field(ge=0.0, le=1.0, description="Classification confidence score")
    matched_keywords: list[str] = Field(default_factory=list)
    requires_escalation: bool = False
    escalation_reason: Optional[str] = None


class PatientInquiry(BaseModel):
    """Incoming patient inquiry."""
    session_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    inquiry_text: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    patient_id: Optional[str] = None  # Anonymized patient reference
    channel: str = "api"  # api, chat, voice


class AgentResponse(BaseModel):
    """Response generated by a specialized agent."""
    session_id: str
    agent_type: AgentType
    response_text: str
    actions_taken: list[str] = Field(default_factory=list)
    requires_escalation: bool = False
    escalation_priority: Optional[EscalationPriority] = None
    escalation_reason: Optional[str] = None
    confidence: float = Field(ge=0.0, le=1.0, default=1.0)
    metadata: dict = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class GuardrailResult(BaseModel):
    """Result of a guardrail check on an agent response."""
    guardrail_name: str
    status: GuardrailStatus
    violations: list[str] = Field(default_factory=list)
    details: str = ""
    original_response: Optional[str] = None
    sanitized_response: Optional[str] = None


class EscalationRequest(BaseModel):
    """Request to escalate to a human agent."""
    session_id: str
    priority: EscalationPriority
    reason: str
    context_summary: str
    original_inquiry: str
    agent_type: AgentType
    conversation_history: list[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class AuditLogEntry(BaseModel):
    """Structured audit log entry for compliance tracking."""
    log_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    session_id: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    event_type: str  # inquiry_received, agent_routed, guardrail_check, response_sent, escalation
    agent_type: Optional[AgentType] = None
    intent_classification: Optional[IntentClassification] = None
    guardrail_results: list[GuardrailResult] = Field(default_factory=list)
    escalation: Optional[EscalationRequest] = None
    response_time_ms: Optional[float] = None
    anonymized_inquiry: Optional[str] = None
    details: dict = Field(default_factory=dict)


class MetricEvent(BaseModel):
    """A single metric data point for tracking."""
    metric_name: str
    value: float
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    tags: dict = Field(default_factory=dict)


class AlertEvent(BaseModel):
    """An alert triggered by the monitoring system."""
    alert_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    severity: AlertSeverity
    title: str
    description: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    session_id: Optional[str] = None
    agent_type: Optional[AgentType] = None
    resolved: bool = False


class SystemHealthStatus(BaseModel):
    """Overall system health status."""
    status: str = "healthy"
    active_sessions: int = 0
    total_inquiries_processed: int = 0
    uptime_seconds: float = 0.0
    agents_status: dict = Field(default_factory=dict)
    guardrails_status: dict = Field(default_factory=dict)
    last_check: datetime = Field(default_factory=datetime.utcnow)


# ─── API Request/Response Models ────────────────────────────────────────────


class InquiryRequest(BaseModel):
    """API request to submit a patient inquiry."""
    inquiry_text: str = Field(min_length=1, max_length=2000)
    patient_id: Optional[str] = None
    channel: str = "api"


class InquiryResponse(BaseModel):
    """API response for a patient inquiry."""
    session_id: str
    response_text: str
    category: InquiryCategory
    was_escalated: bool = False
    escalation_priority: Optional[EscalationPriority] = None
    response_time_ms: float
    guardrails_passed: bool = True
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class MetricsSummary(BaseModel):
    """Summary of system metrics for the dashboard."""
    total_inquiries: int = 0
    avg_response_time_ms: float = 0.0
    first_contact_resolution_rate: float = 0.0
    escalation_rate: float = 0.0
    guardrail_compliance_rate: float = 0.0
    inquiries_by_category: dict = Field(default_factory=dict)
    active_alerts: int = 0
    period: str = "all_time"
